services:
  openvidu-server:
    image: openvidu/openvidu-server-kms:2.23.0
    container_name: openvidu-server
    ports:
      - "4443:4443"
      - "3478:3478/udp"
    environment:
      - OPENVIDU_SECRET=MY_SECRET
      - DOMAIN_OR_PUBLIC_IP=d204test.p-e.kr
      - HTTPS_PORT=443
      - CERTIFICATE_TYPE=letsencrypt
      - LETSENCRYPT_EMAIL=your-eddy152264@gmail.com
    volumes:
      - ./certificates:/etc/letsencrypt
      - ./data:/openvidu/recordings
    networks:
      - openvidu-net

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - /home/ubuntu/openvidu/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/openvidu/frontend/public:/usr/share/nginx/html
    container_name: nginx
    networks:
      - openvidu-net

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: frontend
    volumes:
      - /home/ubuntu/openvidu/frontend/public:/opt/openvidu-basic-node/public
    environment:
      - OPENVIDU_URL=https://d204test.p-e.kr
      - OPENVIDU_SECRET=MY_SECRET
    depends_on:
      - openvidu-server
    networks:
      - openvidu-net

  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - OPENVIDU_URL=https://d204test.p-e.kr
      - OPENVIDU_SECRET=MY_SECRET
      - SERVER_SSL_ENABLED=true
    depends_on:
      - openvidu-server
    networks:
      - openvidu-net

networks:
  openvidu-net:
    driver: bridge